### PR TITLE
[WIP] Fix Continuous Integration

### PR DESCRIPTION
**Pull request by danlamanna**
The goals of this PR are:
- [x] Separate travis into building/testing Flow with R dependencies and without
- [ ] Replace Tangelo 0.7 with CherryPy for serving test app
 - This is essentially a stopgap until Flow becomes a full fledged Girder plugin
- [ ] Ensure all tests are passing
 - Right now JS coverage is failing, because web_client_app is failing.

Current blocker is getting CherryPy to correctly serve Flow and Girder within the testing environment. Right now the tests fail because the server is stopped by the time the tests run, but running locally I can block CherryPy and actually run the tests (some still fail, but at least they run).

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I wish you the best on your quest for code quality. It is a noble quest. I hope you come out unharmed on the other side.

**Comment by zachmullen** [comment]
The R process is still broken (wasn't sure how to fix that), but I updated the girder part so that it works with 1.4.1 using a more modern npm.

**Comment by danlamanna** [comment]
@zachmullen @manthey Jeff suggested I bug you guys - the tests are running in travis, see [here](https://travis-ci.org/Kitware/flow/jobs/94730041), the only issue is CherryPy isn't exiting when it's supposed to (I have to manually cancel the travis jobs). Have either of you run into something like this?

**Comment by zachmullen** [comment]
Try replacing `cherrypy.server.start()` with `cherrypy.engine.start()` in base.py.

**Comment by danlamanna** [comment]
I experimented with server/engine earlier since that's what Girder does, but if I use ```engine.start``` CherryPy stops serving requests before phantom gets a chance to run.

**Comment by zachmullen** [comment]
Have you tried removing the call to `unsubscribe()` in conjunction with `cherrypy.engine.start()`?

**Comment by danlamanna** [comment]
Yes - the same issue persists then (CherryPy shuts down before tests get to run). I just don't want to waste too much time if this is eventually going to turn into a Girder plugin and leverage their CherryPy implementation.

**Pull request closed without merging**
