### PR TITLE
Run the static extras grunt task by default

### LINKED ISSUE #192: Vega scatterplot plugin doesn't work anymore
I looks like the Vega spec definition file is missing or the URL became corrupted:

GET http://localhost:8080/static/built/plugins/flow/extras/scatterplot.json 404 (Not Found)
vg.parse.spec [Vega Err] [object XMLHttpRequest]

### PR DESCRIPTION
**Pull request by danlamanna**
Fixes #192 

@jeffbaumes @curtislisle

### CODE REVIEW

**Comment by jeffbaumes** [comment]
When I do a clean `vagrant up` and try to make a scatterplot, I get:

```
d3.js:1919 GET http://localhost:8080/static/built/plugins/flow/extras/scatterplot.json 404 (Not Found)
```

So it seems it is still not there or in the wrong spot?

**Comment by danlamanna** [comment]
It's a little wonky doing PRs revolving around the ansible scripts, since your clean vagrant up checks out `flow_version` which is still master (unless you change it to `fix-static-extras-404`).

**Comment by jeffbaumes** [comment]
Ok retrying this now ...

**Comment by jeffbaumes** [comment]
Worked that time - LGTM.

**Pull request merged**
