### PR TITLE
Switch to girder worker

### PR DESCRIPTION
**Pull request by danlamanna**
This switches Flow from using Romanesco to using Girder Worker with the "Worker" plugin in Girder.

All of the Flow-exclusive Romanesco bits have now been moved into Flow with the understanding that general enough pieces will eventually be moved into the worker plugin once they have been well tested.

The only configuration difference here is that we're using RMQ instead of Mongo as our broker for Celery.

It also required some changes like web_client became web_external (which it should be), and the only thing in web_client now is the configuration view.

### CODE REVIEW

**Comment by danlamanna** [comment]
@jeffbaumes PTAL

**Comment by jeffbaumes** [comment]
This is looking good. I've verified that the Flow plugin settings for authorization seem to be working.

I did find one bug with `select2`. If there is just a single analysis in a collection and you have done a page refresh and click the eyeball for just that collection, it does not seem to show the name of that analysis in the dropdown, and selecting it does not change what shows in the dropdown (i.e. it is always blank).

**Comment by jeffbaumes** [comment]
The `vagrant up` provisioning seems to have an issue. When creating a simple Python script and running it, I'm getting this on the `status` endpoint

```json
{"message": "None: Max retries exceeded with url: /api/v1/job/570bf2e40640fd11a51097e2 (Caused by None)", "status": "FAILURE"}
```

**Comment by danlamanna** [comment]
@jeffbaumes I will ping you at some point. Fixed the select2 issue, can't replicate the status endpoint failure.

**Comment by danlamanna** [comment]
@jeffbaumes Still can not reproduce that status endpoint failure on a totally clean vagrant up.

**Comment by jeffbaumes** [comment]
Looks like it's on me to try to reproduce on a fully clean version - I'll do that now.

**Comment by jeffbaumes** [comment]
Getting the same error on my side - are either of these versions a possible culprit?

```
$ ansible --version
ansible 1.9.4
  configured module search path = None
$ vagrant --version
Vagrant 1.8.1
```

**Comment by danlamanna** [comment]
@jeffbaumes Works with those versions on both of my machines - I think we may have to debug this on your machine.

**Comment by jeffbaumes** [comment]
In `/var/log/girder_worker.log` there is this

```
[2016-04-18 18:15:08,927: ERROR/MainProcess] Task girder_worker.run[35d9e404-a9f1-4df8-8f26-4b9fa06e3e2b] raised unexpected: ConnectionError(MaxRetryError('None: Max retries exceeded with url: /api/v1/job/5715242c0640fd12cbbaf749 (Caused by None)',),)
Traceback (most recent call last):
  File "/opt/.girderenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/girder_worker/girder_worker/__main__.py", line 28, in run
    retval = girder_worker.run(*pargs, **kwargs)
  File "girder_worker/utils.py", line 117, in __exit__
    self.updateStatus(JobStatus.ERROR)
  File "girder_worker/utils.py", line 192, in updateStatus
    data={'status': status}, allow_redirects=True)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: None: Max retries exceeded with url: /api/v1/job/5715242c0640fd12cbbaf749 (Caused by None)
[2016-04-19 11:41:28,416: WARNING/Worker-1] <class 'requests.exceptions.ConnectionError'>: HTTPConnectionPool(host='localhost', port=9999): Max retries exceeded with url: /api/v1/job/571619680640fd12cbbaf74b (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0eb7530c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
  File "/opt/girder_worker/girder_worker/__main__.py", line 28, in run
    retval = girder_worker.run(*pargs, **kwargs)
  File "girder_worker/utils.py", line 295, in wrapped
    return fn(*args, **kwargs)
  File "girder_worker/__init__.py", line 294, in run
    _job_status(job_mgr, status)
  File "girder_worker/__init__.py", line 163, in _job_status
    mgr.updateStatus(status)
  File "girder_worker/utils.py", line 192, in updateStatus
    data={'status': status}, allow_redirects=True)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/.girderenv/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
```

Seeing the `9999` in there makes me think it's because I changed the `host` forwarded port in the `Vagrantfile`. Perhaps the `host` and `guest` ports need to match. Retrying now with it set to the default `8080`.

**Comment by jeffbaumes** [comment]
That was it. Changing it back to `8080` made it work.

LGTM.

**Pull request merged**
